### ISSUE TITLE
New Tricks & Scripts (Hacktoberfest)

### ISSUE THREAD

**Issue by EmreOvunc** [EmreOvunc/Linux-System-Management-Scripts-Tricks#1]
Hello Everyone,

To participate in Hacktoberfest, you can help me to add new scripts or tricks to Linux System Management repository.

**Note: The important thing is that your codes or samples should be reproducible easily and they are verified.**

Feel free to open PR :)
_(All PRs which have been verified, will be merged on October 1, 2020)_

For instance: https://github.com/EmreOvunc/Linux-System-Management-Scripts-Tricks/commit/6640a27c6a074a70c71c969634beebe944efa54a

Happy Hacktoberfest
#hacktoberfest2020

**Comment by ghost** [comment]
Hellow ! I have include my software `aliaz` it's a alias creator for linux, in bash, CLI and GUI available.

You can refer [here](https://github.com/72y9op/aliaz) can i PR it ?

**Comment by EmreOvunc** [comment]
> Hellow ! I have include my software `aliaz` it's a alias creator for linux, in bash, CLI and GUI available.
> 
> You can refer [here](https://github.com/72y9op/aliaz) can i PR it ?

Hellow :) 

I reviewed your project, it seems successful. I would appreciate if you could get a PR on **how to add Alias** to the [Others](https://github.com/EmreOvunc/Linux-System-Management-Scripts-Tricks#Others) Part, because in this repo I don't want to add GUI based things.
For instance: 
```
#nano ~/.bashrc
alias myip='curl ipinfo.io/ip'
source ~/.bashrc
```

**Comment by ghost** [comment]
Hello ! 
The update 3.0.0 offers the possibility of **one-line** command, I suggest you work on a special version of aliaz for your project !

Exemple of "one-line" command :
`mkalias --name="myip" --command="curl ipinfo.io/ip"`

Would that suit you?

**Comment by EmreOvunc** [comment]
> Hello !
> The update 3.0.0 offers the possibility of **one-line** command, I suggest you work on a special version of aliaz for your project !
> 
> Exemple of "one-line" command :
> `mkalias --name="myip" --command="curl ipinfo.io/ip"`
> 
> Would that suit you?

Innovation is nice to have, you are welcome :)

**Comment by ghost** [comment]
@EmreOvunc Hellow ! I have finally finished the version, I will put it on the fork of your project tomorrow, you can tell me if I have the right to do a PR ?

**Comment by EmreOvunc** [comment]
> @EmreOvunc Hellow ! I have finally finished the version, I will put it on the fork of your project tomorrow, you can tell me if I have the right to do a PR ?

You can open a PR whenever you want :)
